#!/bin/sh

# Runs code generation. Use: `./run generate` or `./run generate watch`` in project dir.
if [[ $1 == "generate" ]]; then
    if [[ $2 == "watch" ]]; then
        flutter pub run build_runner watch --delete-conflicting-outputs
    else
        flutter pub run build_runner build --delete-conflicting-outputs
    fi
fi
